/*
 * Copyright OmniFaces
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 */
package org.omnifaces.test.viewhandler;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.DisabledIfSystemProperty;
import org.omnifaces.test.OmniFacesIT;

/**
 * Verifies that an automatically generated component ID in the rendered output fails the render during development stage, while a view whose components all
 * carry an explicit ID renders as usual.
 */
public class NoAutoGeneratedIdResponseWriterIT extends OmniFacesIT {

    @Deployment(testable = false)
    public static WebArchive createDeployment() {
        return buildWebArchive(NoAutoGeneratedIdResponseWriterIT.class)
            .withFacesConfig(FacesConfig.withNoAutoGeneratedIdViewHandler)
            .withWebXml(WebXml.withDevelopmentStage)
            .createDeployment();
    }

    @Test
    void testAllIdsPresent() {
        verify200("AllIdsPresent.xhtml");
    }

    @Test
    @DisabledIfSystemProperty(
        named = "profile.id", matches = "quarkus-.*", disabledReason = "quarkus test mode ignores error-page in web.xml and instead uses own one (works in non-test)"
    )
    @DisabledIfSystemProperty(
        named = "profile.id", matches = "liberty-.*", disabledReason = "liberty ignores error-page in web.xml when the response writer throws and instead uses own one"
    )
    void testFormWithoutId() {
        verify500("FormWithoutId.xhtml");
    }

    @Test
    @DisabledIfSystemProperty(
        named = "profile.id", matches = "quarkus-.*", disabledReason = "quarkus test mode ignores error-page in web.xml and instead uses own one (works in non-test)"
    )
    @DisabledIfSystemProperty(
        named = "profile.id", matches = "liberty-.*", disabledReason = "liberty ignores error-page in web.xml when the response writer throws and instead uses own one"
    )
    void testInputWithoutId() {
        verify500("InputWithoutId.xhtml");
    }

    private void verify200(String path) {
        open(path);
        assertEquals(path, browser.getTitle());
    }

    private void verify500(String path) {
        open(path);
        assertEquals("500", browser.getTitle());
    }

}
