/*
 * Copyright OmniFaces
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 */
package org.omnifaces.facesviews;

import static jakarta.servlet.DispatcherType.FORWARD;
import static jakarta.servlet.DispatcherType.REQUEST;
import static java.lang.Boolean.parseBoolean;
import static java.util.Collections.unmodifiableMap;
import static java.util.Collections.unmodifiableSet;
import static java.util.Locale.US;
import static java.util.regex.Pattern.quote;
import static java.util.stream.Collectors.toMap;
import static org.omnifaces.facesviews.ExtensionAction.REDIRECT_TO_EXTENSIONLESS;
import static org.omnifaces.facesviews.PathAction.SEND_404;
import static org.omnifaces.util.Faces.getServletContext;
import static org.omnifaces.util.Platform.getFacesServletMappings;
import static org.omnifaces.util.Platform.getFacesServletRegistration;
import static org.omnifaces.util.Reflection.findMethod;
import static org.omnifaces.util.ResourcePaths.addLeadingSlashIfNecessary;
import static org.omnifaces.util.ResourcePaths.addTrailingSlashIfNecessary;
import static org.omnifaces.util.ResourcePaths.filterExtension;
import static org.omnifaces.util.ResourcePaths.getExtension;
import static org.omnifaces.util.ResourcePaths.isDirectory;
import static org.omnifaces.util.ResourcePaths.isExtensionless;
import static org.omnifaces.util.ResourcePaths.isRoot;
import static org.omnifaces.util.ResourcePaths.stripExtension;
import static org.omnifaces.util.ResourcePaths.stripPrefixPath;
import static org.omnifaces.util.ResourcePaths.stripTrailingSlash;
import static org.omnifaces.util.Servlets.getApplicationAttribute;
import static org.omnifaces.util.Servlets.getRequestBaseURL;
import static org.omnifaces.util.Utils.csvToList;
import static org.omnifaces.util.Utils.isEmpty;
import static org.omnifaces.util.Utils.startsWithOneOf;
import static org.omnifaces.util.Xml.getNodeTextContents;

import java.io.IOException;
import java.net.URL;
import java.util.Collection;
import java.util.EnumSet;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;
import java.util.logging.Logger;

import jakarta.faces.application.Application;
import jakarta.faces.application.ConfigurableNavigationHandler;
import jakarta.faces.application.ViewHandler;
import jakarta.faces.context.FacesContext;
import jakarta.faces.webapp.FacesServlet;
import jakarta.servlet.FilterRegistration;
import jakarta.servlet.ServletContext;
import jakarta.servlet.ServletRegistration;
import jakarta.servlet.http.HttpServletRequest;

import org.omnifaces.ApplicationInitializer;
import org.omnifaces.ApplicationListener;
import org.omnifaces.ApplicationProcessor;
import org.omnifaces.cdi.Param;
import org.omnifaces.component.output.PathParam;
import org.omnifaces.util.Servlets;

/**
 * <p>
 * FacesViews is a mechanism to use SEO-friendly extensionless URLs in a Faces application without the need to enlist individual Facelet source files in some
 * configuration file.
 * <p>
 * All files found in the scanned directories are automatically mapped as Facelets files and made available using both their original extension as well as
 * without an extension. By default, all URLs generated by {@link ViewHandler#getActionURL(FacesContext, String)}, which is used by among others
 * <code>&lt;h:form&gt;</code>, <code>&lt;h:link&gt;</code>, <code>&lt;h:button&gt;</code> and all extended tags, will also be extensionless. And, URLs with an
 * extension will be 301-redirected to the extensionless one.
 * <p>
 * Scanning is done automatically and the feature is compatible with applications that have no <code>web.xml</code> or <code>faces-config.xml</code>. As such it
 * can be used as an alternative to declaring the {@link FacesServlet} in <code>web.xml</code> for the <code>.xhtml</code> to <code>.xhtml</code> mapping, which
 * additionally prevents exposing the source code of those Facelets that happens with the default Faces mapping.
 *
 * <h2 id="usage"><a href="#usage">Usage</a></h2>
 *
 * <h3 id="zero-configuration"><a href="#zero-configuration">Zero configuration</a></h3>
 * <p>
 * Put Facelets source files into the <code>/WEB-INF/faces-views</code> directory. All Facelets files in this special directory will be automatically scanned as
 * extensionless URLs. Given the following file structure:
 *
 * <pre>
 * /WEB-INF/faces-views/index.xhtml
 * /WEB-INF/faces-views/users/add.xhtml
 * /normal.xhtml
 * </pre>
 * <p>
 * the Facelets are available via the following URLs, given a root deployment on domain <code>example.com</code>:
 *
 * <pre>
 * example.com/index
 * example.com/users/add
 * example.com/index.xhtml       (301-redirects to /index by default)
 * example.com/users/add.xhtml   (301-redirects to /users/add by default)
 * example.com/normal.xhtml
 * </pre>
 * <p>
 * Note that although the directory outside <code>/WEB-INF/faces-views</code> is not scanned, the {@link FacesServlet} <em>is</em> mapped on all extensions
 * found in <code>/WEB-INF/faces-views</code>, so this also affects files outside this directory. In the above example <code>/normal.xhtml</code> is thus also
 * available via the <code>.xhtml</code> extension. Whether the extension variant of a scanned view redirects to the extensionless one, is configurable via
 * {@link #FACES_VIEWS_EXTENSION_ACTION_PARAM_NAME}.
 *
 * <h3 id="minimal-configuration"><a href="#minimal-configuration">Minimal configuration</a></h3>
 * <p>
 * Below is the minimal <code>web.xml</code> configuration to make all Facelets source files found in the root folder and all subdirectories of the public web
 * content (excluding <code>/WEB-INF</code>, <code>/META-INF</code> and <code>/resources</code>) available as extensionless URLs:
 *
 * <pre>
 * &lt;context-param&gt;
 *     &lt;param-name&gt;org.omnifaces.FACES_VIEWS_SCAN_PATHS&lt;/param-name&gt;
 *     &lt;param-value&gt;/*.xhtml&lt;/param-value&gt;
 * &lt;/context-param&gt;
 * </pre>
 * <p>
 * The path pattern <code>/*.xhtml</code> basically means that all files with the <code>.xhtml</code> extension from the directory <code>/</code> must be
 * scanned, including all sub directories. In case you want to scan only <code>.xhtml</code> files in the directory <code>/foo</code>, then use path pattern of
 * <code>/foo/*.xhtml</code> instead. In case you want to scan <em>all</em> files in the directory <code>/foo</code>, then use path pattern of
 * <code>/foo</code>. You can specify multiple values separated by a comma. Given the following file structure:
 *
 * <pre>
 * /page1.xhtml
 * /foo/page2.xhtml
 * /WEB-INF/resources/template.xhtml
 * /script.js
 * </pre>
 * <p>
 * the Facelets are available via the following URLs:
 *
 * <pre>
 * example.com/page1
 * example.com/foo/page2
 * example.com/page1.xhtml       (301-redirects to /page1 by default)
 * example.com/foo/page2.xhtml   (301-redirects to /foo/page2 by default)
 * </pre>
 * <p>
 * Note that <code>/WEB-INF</code> is not scanned and thus <code>template.xhtml</code> is not made publicly available. Likewise <code>/script.js</code> is not
 * scanned either as it doesn't have the configured extension. Finally, although a <code>web.xml</code> is used, there does not need to be a mapping for the
 * {@link FacesServlet} in it.
 *
 * <h3 id="multiviews-configuration"><a href="#multiviews-configuration">MultiViews configuration</a></h3>
 * <p>
 * A MultiViews view swallows any trailing path segments and exposes them as positional path parameters. Enabling it is a matter of suffixing the path pattern
 * with <code>/*</code>. The support was added in OmniFaces 2.5. Below is the <code>web.xml</code> configuration which extends the above minimal configuration
 * with MultiViews support:
 *
 * <pre>
 * &lt;context-param&gt;
 *     &lt;param-name&gt;org.omnifaces.FACES_VIEWS_SCAN_PATHS&lt;/param-name&gt;
 *     &lt;param-value&gt;/*.xhtml/*&lt;/param-value&gt;
 * &lt;/context-param&gt;
 * </pre>
 * <p>
 * On an example URL of <code>https://example.com/context/foo/bar/baz</code> when neither <code>/foo/bar/baz.xhtml</code> nor <code>/foo/bar.xhtml</code> exist,
 * but <code>/foo.xhtml</code> does exist, then the request will forward to <code>/foo.xhtml</code> and make the values <code>bar</code> and <code>baz</code>
 * available as injectable path parameters via <code>&#64;</code>{@link Param} in the managed bean associated with <code>/foo.xhtml</code>.
 *
 * <pre>
 *
 * &#64;Inject
 * &#64;Param(pathIndex = 0)
 * private String bar;
 *
 * &#64;Inject
 * &#64;Param(pathIndex = 1)
 * private String baz;
 * </pre>
 * <p>
 * MultiViews can be enabled on a subset of the scanned views by suffixing only the path pattern concerned. A path pattern of <code>/*.xhtml, /foo/*</code> thus
 * scans every <code>.xhtml</code> file but enables MultiViews only on the files in <code>/foo</code>, so that <code>example.com/foo/page2/bar</code> forwards
 * to <code>/foo/page2.xhtml</code> while <code>example.com/page1/bar</code> does not resolve at all.
 *
 * <h3 id="dynamic-routes-configuration"><a href="#dynamic-routes-configuration">Dynamic routes configuration</a></h3>
 * <p>
 * A directory whose name is wrapped in square brackets is a dynamic route segment. It matches exactly one path segment and exposes it under the bracketed name.
 * The support was added in OmniFaces 5.5 and needs no configuration beyond the scan path above. Given the following file structure:
 *
 * <pre>
 * /organizations/[id]/index.xhtml
 * /organizations/[id]/members.xhtml
 * /organizations/settings/members.xhtml
 * </pre>
 * <p>
 * the Facelets are available via the following URLs:
 *
 * <pre>
 * example.com/organizations/123                (forwards to /organizations/[id]/index.xhtml with segment "id" being "123")
 * example.com/organizations/123/members        (forwards to /organizations/[id]/members.xhtml with segment "id" being "123")
 * example.com/organizations/settings/members   (forwards to /organizations/settings/members.xhtml without any segment)
 * </pre>
 * <p>
 * The segment value is available as an injectable path parameter via <code>&#64;</code>{@link Param} in the managed bean associated with the forwarded view.
 *
 * <pre>
 *
 * &#64;Inject
 * &#64;Param(pathName = "id")
 * private String id;
 * </pre>
 * <p>
 * A dynamic route directory needs no welcome file, in which case only the views inside it answer and the bare <code>/organizations/123</code> does not resolve.
 * The first URL above thus additionally requires an extensionless <a href="#welcome-files">welcome file</a>.
 * <p>
 * A request path is resolved by first looking for an exact match among the scanned views, then walking the dynamic route segments, and only then falling back
 * to MultiViews. A literal directory is always preferred over a dynamic one at the same level, which means a literal sibling is a value the dynamic segment can
 * never take: in the above example an organization whose id is <code>settings</code> is unreachable. An application without any bracketed directory never
 * reaches the dynamic route resolution at all and therefore behaves exactly as before.
 * <p>
 * Dynamic route segments nest and compose with MultiViews, so <code>/[locale]/products/[sku]/reviews.xhtml</code> answers to
 * <code>/nl/products/12345/reviews/2</code> with <code>nl</code> and <code>12345</code> available by name and <code>2</code> available as
 * <code>&#64;Param(pathIndex = 0)</code>.
 * <p>
 * Note that only a <em>directory</em> name is interpreted this way. A bracketed <em>file</em> name such as <code>[id].xhtml</code> is scanned literally and
 * logged as a warning, as square brackets are gen-delims per RFC 3986 which containers may refuse in a URL outright. For the same reason, a link to a dynamic
 * route is rendered with every segment substituted, which is why <code>&lt;o:pathParam name&gt;</code> must supply them, see {@link PathParam}.
 * <p>
 * Three configurations have no correct interpretation and fail the deployment:
 *
 * <ul>
 * <li>Two differently named dynamic route segments under the same parent, e.g. <code>/organizations/[id]</code> next to <code>/organizations/[slug]</code>, as
 * there is no defensible way to choose between them.
 * <li>The same segment name twice in one path, e.g. <code>/[id]/foo/[id]/bar</code>, as a path parameter is addressed by name and could then not address both.
 * <li>An unbalanced or empty square bracket pair in a directory name, e.g. <code>[id</code> or <code>[]</code>.
 * </ul>
 *
 * <h3 id="welcome-files"><a href="#welcome-files">Welcome files</a></h3>
 * <p>
 * If a <code>&lt;welcome-file&gt;</code> is defined in <code>web.xml</code> that's scanned by FacesViews <strong>and</strong> the default
 * <code>REDIRECT_TO_EXTENSIONLESS</code> extension action is used, then it's necessary to define an extensionless welcome file to prevent a request to
 * <code>/</code> being redirected to <code>/[welcome file]</code>. E.g. without this <code>https://example.com</code> will redirect to
 * <code>https://example.com/index</code>.
 *
 * <pre>
 * &lt;welcome-file-list&gt;
 *     &lt;welcome-file&gt;index&lt;/welcome-file&gt;
 * &lt;/welcome-file-list&gt;
 * </pre>
 * <p>
 * This is also what makes the bare URL of a directory answer to the welcome file inside it, which includes a dynamic route directory, as in
 * <code>/organizations/[id]/index.xhtml</code> answering to <code>/organizations/123</code>.
 * <p>
 * If you're using MultiViews on a site-wide basis and have a welcome file configured for it, then basically any request which doesn't match any physical file
 * will end up in that welcome file. In case this is undesirable, because you're having e.g. a REST API listening on <code>/api/*</code> or a websocket endpoint
 * listening on <code>/push/*</code>, then you can configure them as an exclude pattern as below:
 *
 * <pre>
 * &lt;context-param&gt;
 *     &lt;param-name&gt;org.omnifaces.FACES_VIEWS_SCAN_PATHS&lt;/param-name&gt;
 *     &lt;param-value&gt;/*.xhtml/*, !/api, !/push&lt;/param-value&gt;
 * &lt;/context-param&gt;
 * </pre>
 *
 * <h3 id="dispatch-methods"><a href="#dispatch-methods">Dispatch methods</a></h3>
 * <p>
 * Faces normally inspects the request URI to derive a logical view id from it. It assumes the {@link FacesServlet} is either mapped on a prefix path or an
 * extension, and will get confused when an extensionless "exactly mapped" request is encountered. To counter this, FacesViews makes use of
 * {@link FacesViewsForwardingFilter} which intercepts each request and makes it appear to Faces that the request was a normal extension mapped one.
 * <p>
 * Two dispatch methods are used to do this: forwarding, and wrapping the request and continuing the filter chain. For the latter the {@link FacesServlet} is
 * programmatically mapped to every individual scanned view. A dynamic route is not expressible as a servlet URL pattern, as the specification has only exact,
 * prefix, extension and default mappings, and is therefore always resolved by forwarding.
 * <p>
 * These internal details are important to be aware of, since they greatly influence how extensionless requests interact with other filter based functionality
 * such as security filters, compression filters, file upload filters, etcetera. With the forwarding method, such filters typically have to be set to dispatch
 * type <code>FORWARD</code> as well. The FacesViews filter is by default the first in the chain, so other filters which are set to dispatch type
 * <code>REQUEST</code> are then not invoked at all, as the chain is ended. Set {@link #FACES_VIEWS_FILTER_AFTER_DECLARED_FILTERS_PARAM_NAME} to place it after
 * the filters declared in <code>web.xml</code>, in which case those are invoked, but they should not modify the response, as a forward clears the response
 * buffer so far when it is not yet committed.
 *
 * <h2 id="configuration"><a href="#configuration">Configuration</a></h2>
 * <p>
 * The following context parameters are available.
 *
 * <table border="1">
 * <caption>All available context parameters</caption>
 *
 * <tr>
 * <td class="colFirst"><code>{@value #FACES_VIEWS_ENABLED_PARAM_NAME}</code></td>
 * <td>Used to completely switch scanning off. <br>
 * Allowed values: {<code>true</code>,<code>false</code>} <br>
 * Default value: <code>true</code> <br>
 * (note that if no <code>/WEB-INF/faces-views</code> directory is present and no explicit paths have been configured, no scanning will be done either)</td>
 * </tr>
 *
 * <tr>
 * <td class="colFirst"><code>{@value #FACES_VIEWS_SCAN_PATHS_PARAM_NAME}</code></td>
 * <td>A comma separated list of paths that are to be scanned in addition to <code>/WEB-INF/faces-views</code>. <br>
 * Allowed values: any path relative to the web root, including the root path (<code>/</code>) and <code>/WEB-INF</code>. A wildcard can be added to the path,
 * which will cause only files with the given extension te be scanned. <br>
 * Examples: <br>
 * - Scan all files in both folder1 and folder2: <code>/folder1, /folder2</code> <br>
 * - Scan only .xhtml files in the root: <code>/*.xhtml</code> <br>
 * Note that when the root path is given, all its sub paths are also scanned EXCEPT <code>WEB-INF</code>, <code>META-INF</code> and <code>resources</code>. If
 * those have to be scanned as well, they can be added to the list of paths explicitly. <br>
 * Default value: <code>/WEB-INF/faces-views</code> (note when this value is set, those paths will be in addition to the default
 * <code>/WEB-INF/faces-views</code>)</td>
 * </tr>
 *
 * <tr>
 * <td class="colFirst"><code>{@value #FACES_VIEWS_SCANNED_VIEWS_EXTENSIONLESS_PARAM_NAME}</code></td>
 * <td>Used to set how scanned views should be rendered in Faces controlled links. With this setting set to <code>false</code>, it depends on whether the
 * request URI uses an extension or not. If it doesn't, links are also rendered without one, otherwise they are rendered with an extension. When set to
 * <code>true</code> links are always rendered without an extension. <br>
 * Default value: <code>true</code></td>
 * </tr>
 *
 * <tr>
 * <td class="colFirst"><code>{@value #FACES_VIEWS_EXTENSION_ACTION_PARAM_NAME}</code></td>
 * <td>Determines the action that is performed whenever a resource is requested WITH extension that's also available without an extension. <br>
 * Allowed values are enumerated in {@link ExtensionAction}, which have the following meaning: <br>
 * - <code>REDIRECT_TO_EXTENSIONLESS</code>: Send a 301 (permanent) redirect to the same URL, but with the extension removed. E.g. <code>/foo.xhtml</code>
 * redirects to <code>/foo</code>. <br>
 * - <code>SEND_404</code>: Send a 404 (not found), makes it look like e.g. <code>/foo.xhtml</code> never existed and there's only <code>/foo</code>. <br>
 * - <code>PROCEED</code>: No special action is taken. Both <code>/foo.xhtml</code> and <code>/foo</code> are processed as-if they were separate views (with
 * same content). <br>
 * Default value: <code>REDIRECT_TO_EXTENSIONLESS</code></td>
 * </tr>
 *
 * <tr>
 * <td class="colFirst"><code>{@value #FACES_VIEWS_PATH_ACTION_PARAM_NAME}</code></td>
 * <td>Determines the action that is performed whenever a resource is requested in a public path that has been used for scanning views by faces views (e.g. the
 * paths set by <code>{@value #FACES_VIEWS_SCAN_PATHS_PARAM_NAME}</code>, but excluding the root path /). <br>
 * Allowed values are enumerated in {@link PathAction}, which have the following meaning: <br>
 * - <code>SEND_404</code>: Send a 404 (not found), makes it look like e.g. <code>/path/foo.xhtml</code> never existed and there's only <code>/foo</code> and
 * optionally <code>/foo.xhtml</code>. <br>
 * - <code>REDIRECT_TO_SCANNED_EXTENSIONLESS</code>: Send a 301 (permanent) redirect to the resource corresponding with the one that was scanned. E.g.
 * <code>/path/foo.xml</code> redirects to <code>/foo</code>. <br>
 * - <code>PROCEED</code>: No special action is taken. <code>/path/foo.xml</code> and <code>/foo</code> (and optionally <code>/foo.xhtml</code>) will be
 * accessible. <br>
 * Default value: <code>SEND_404</code></td>
 * </tr>
 *
 * <tr>
 * <td class="colFirst"><code>{@value #FACES_VIEWS_FILTER_AFTER_DECLARED_FILTERS_PARAM_NAME}</code></td>
 * <td>Used to set whether the {@link FacesViewsForwardingFilter} should match before declared filters (<code>false</code>) or after declared filters
 * (<code>true</code>). <br>
 * Default value: <code>false</code> (the FacesViews forwarding filter is the first in the filter chain)</td>
 * </tr>
 *
 * <tr>
 * <td class="colFirst"><code>{@value #FACES_VIEWS_LOWERCASED_REQUEST_URI_PARAM_NAME}</code></td>
 * <td>Used to set whether the request URI should only match the lowercased form of the file name. By default, a scanned view of for example
 * <code>/TitleCasedFileName.xhtml</code> will listen to a request URI of <code>/TitleCasedFileName</code>, but when this setting is set to true, then it will
 * instead listen to a lowercased request URI of <code>/titlecasedfilename</code>. <br>
 * Default value: <code>false</code> (the request URI must exactly match the letter case of the file name)</td>
 * </tr>
 *
 * </table>
 *
 * <h2 id="prettyfaces"><a href="#prettyfaces">PrettyFaces</a></h2>
 * <p>
 * Note that there is some overlap between this feature and <a href="https://ocpsoft.org/prettyfaces">PrettyFaces</a>. The difference is that FacesViews has a
 * focus on zero- or very minimal config, where PrettyFaces has a focus on very powerful mapping mechanisms, which of course need some level of configuration.
 * As such FacesViews will only focus on auto discovering views and mapping them to both <code>.xhtml</code> and to no-extension without needing to explicitly
 * declare the {@link FacesServlet} in <code>web.xml</code>.
 * <p>
 * Specifically, FacesViews will thus <em>not</em> become a general URL rewriting tool (e.g. one that maps path segments to parameters, or that totally changes
 * the name of the URL). For this the user is advised to look at the aforementioned <a href="https://ocpsoft.org/prettyfaces">PrettyFaces</a>.
 *
 * @author Arjan Tijms
 * @see FacesViewsResourceHandler
 * @see FacesViewsForwardingFilter
 * @see ExtensionAction
 * @see PathAction
 * @see UriExtensionRequestWrapper
 * @see ApplicationProcessor
 * @see FacesViewsViewHandler
 * @see DynamicRoutesNavigationHandler
 * @see PathParam
 */
public final class FacesViews {

    // Defaults -------------------------------------------------------------------------------------------------------

    /**
     * A special dedicated "well-known" directory where facelets implementing views can be placed. This directory is scanned by convention so that no explicit
     * configuration is needed.
     */
    public static final String WEB_INF_VIEWS = "/WEB-INF/faces-views/";

    // Context parameter names ----------------------------------------------------------------------------------------

    /**
     * The name of the boolean context parameter to switch auto-scanning completely off for Servlet 3.0 containers.
     */
    public static final String FACES_VIEWS_ENABLED_PARAM_NAME = "org.omnifaces.FACES_VIEWS_ENABLED";

    /**
     * The name of the commaseparated context parameter where the value holds a comma separated list of paths that are to be scanned by faces views.
     */
    public static final String FACES_VIEWS_SCAN_PATHS_PARAM_NAME = "org.omnifaces.FACES_VIEWS_SCAN_PATHS";

    /**
     * The name of the boolean context parameter via which the user can set scanned views to be always rendered extensionless. Without this setting (or it being
     * set to false), it depends on whether the request URI uses an extension or not. If it doesn't, links are also rendered without one, otherwise are rendered
     * with an extension.
     */
    public static final String FACES_VIEWS_SCANNED_VIEWS_EXTENSIONLESS_PARAM_NAME = "org.omnifaces.FACES_VIEWS_SCANNED_VIEWS_ALWAYS_EXTENSIONLESS";

    /**
     * The name of the enum context parameter that determines the action that is performed whenever a resource is requested WITH extension that's also available
     * without an extension. See {@link ExtensionAction}
     *
     * @see ExtensionAction
     */
    public static final String FACES_VIEWS_EXTENSION_ACTION_PARAM_NAME = "org.omnifaces.FACES_VIEWS_EXTENSION_ACTION";

    /**
     * The name of the enum context parameter that determines the action that is performed whenever a resource is requested in a public path that has been used
     * for scanning views by faces views. See {@link PathAction}
     *
     * @see PathAction
     */
    public static final String FACES_VIEWS_PATH_ACTION_PARAM_NAME = "org.omnifaces.FACES_VIEWS_PATH_ACTION";

    /**
     * The name of the boolean context parameter via which the user can set whether the {@link FacesViewsForwardingFilter} should match before declared filters
     * (false) or after declared filters (true).
     */
    public static final String FACES_VIEWS_FILTER_AFTER_DECLARED_FILTERS_PARAM_NAME = "org.omnifaces.FACES_VIEWS_FILTER_AFTER_DECLARED_FILTERS";

    /**
     * The name of the boolean context parameter via which the user can set whether the request URI should only match the lowercased form of the file name. By
     * default, a scanned view of for example <code>/TitleCasedFileName.xhtml</code> will listen to a request URI of <code>/TitleCasedFileName</code>, but when
     * this setting is set to true, then it will instead listen to a lowercased request URI of <code>/titlecasedfilename</code>.
     *
     * @since 3.14
     */
    public static final String FACES_VIEWS_LOWERCASED_REQUEST_URI_PARAM_NAME = "org.omnifaces.FACES_VIEWS_LOWERCASED_REQUEST_URI";

    // Request attributes ---------------------------------------------------------------------------------------------

    /**
     * The name of the request attribute under which the original request servlet path is stored.
     */
    public static final String FACES_VIEWS_ORIGINAL_SERVLET_PATH = "org.omnifaces.facesviews.original.servlet_path";

    /**
     * The name of the request attribute under which the original request path info is stored.
     */
    public static final String FACES_VIEWS_ORIGINAL_PATH_INFO = "org.omnifaces.facesviews.original.path_info";

    /**
     * The name of the request attribute under which the resolved dynamic route segment values are stored, as an unmodifiable map of segment name to segment
     * value. It is only present on a request which resolved to a dynamic route.
     *
     * @since 5.5
     */
    public static final String FACES_VIEWS_DYNAMIC_ROUTE_PARAMS = "org.omnifaces.facesviews.dynamic_route_params";

    // Constants ------------------------------------------------------------------------------------------------------

    private static final Logger logger = Logger.getLogger(FacesViews.class.getName());

    private static final String WARNING_UNCONFIGURABLE_NAVIGATION_HANDLER = "The navigation handler '%s' is not a ConfigurableNavigationHandler,"
        + " so an outcome which spells out a dynamic route with its segment values filled in cannot be resolved."
        + " Name the bracketed view as the outcome and supply every segment with a nested <o:pathParam name> instead.";

    private static final String[] RESTRICTED_DIRECTORIES = { "/WEB-INF/", "/META-INF/", "/resources/" };
    private static final String WEB_FRAGMENT_RESOURCE_DIRECTORY = "/META-INF/resources/";

    private static final String ENABLED = "org.omnifaces.facesviews.enabled";
    private static final String SCAN_PATHS = "org.omnifaces.facesviews.scan_paths";
    private static final String PUBLIC_SCAN_PATHS = "org.omnifaces.facesviews.public_scan_paths";
    private static final String FACES_SERVLET_EXTENSIONS = "org.omnifaces.facesviews.faces_servlet_extensions";
    private static final String MAPPED_RESOURCES = "org.omnifaces.facesviews.mapped_resources";
    private static final String REVERSE_MAPPED_RESOURCES = "org.omnifaces.facesviews.reverse_mapped_resources";
    private static final String EXCLUDED_PATHS = "org.omnifaces.facesviews.exclude_paths";
    private static final String ENCOUNTERED_EXTENSIONS = "org.omnifaces.facesviews.encountered_extensions";
    private static final String MAPPED_WELCOME_FILES = "org.omnifaces.facesviews.mapped_welcome_files";
    private static final String FACES_SERVLET_NAME = "org.omnifaces.facesviews.faces_servlet_name";

    private FacesViews() {
        //
    }

    // Initialization -------------------------------------------------------------------------------------------------

    /**
     * This will register the {@link FacesViewsForwardingFilter}. This is invoked by {@link ApplicationInitializer}.
     *
     * @param servletContext The involved servlet context.
     */
    public static void registerForwardingFilter(ServletContext servletContext) {
        if (!isFacesViewsEnabled(servletContext)) {
            return;
        }

        // First scan welcome files in web.xml.
        scanAndStoreWelcomeFiles(servletContext);

        // Scan our dedicated directory for Faces resources that need to be mapped.
        Map<String, String> collectedViews = scanAndStoreViews(servletContext, true);

        if (collectedViews.isEmpty()) {
            return;
        }

        // Register a Filter that forwards extensionless requests to an extension mapped request, e.g. /index to /index.xhtml
        // The FacesServlet doesn't work well with the exact mapping that we use for extensionless URLs.
        FilterRegistration filterRegistration = servletContext.addFilter(FacesViewsForwardingFilter.class.getName(), FacesViewsForwardingFilter.class);
        addForwardingFilterMappings(servletContext, collectedViews, filterRegistration);

        // We now need to map the Faces Servlet to the extensions we found,
        // but at this point in time this Faces Servlet might not be created yet,
        // so we do this part in the FacesViews#addFacesServletMappings() method below,
        // which is called from ApplicationListener#contextInitialized() later.
    }

    private static void addForwardingFilterMappings(ServletContext servletContext, Map<String, String> collectedViews, FilterRegistration filterRegistration) {
        boolean filterAfterDeclaredFilters = parseBoolean(servletContext.getInitParameter(FACES_VIEWS_FILTER_AFTER_DECLARED_FILTERS_PARAM_NAME));

        if (MultiViews.hasWelcomeFile(servletContext)) {
            // When MultiViews is enabled and there are mapped welcome files, we need to filter on /* otherwise path params won't work on root.
            filterRegistration.addMappingForUrlPatterns(EnumSet.of(REQUEST, FORWARD), filterAfterDeclaredFilters, "/*");
        }
        else {
            // Map the forwarding filter to all the resources we found.
            for (var mapping : collectedViews.keySet()) {
                if (!DynamicRoutes.isDynamicRoute(mapping)) {
                    filterRegistration.addMappingForUrlPatterns(EnumSet.of(REQUEST, FORWARD), filterAfterDeclaredFilters, mapping);
                }
            }

            // A dynamic route is not registrable as a URL pattern, so map the filter on the nearest static ancestor of each one instead.
            for (var prefix : DynamicRoutes.get(servletContext).getFilterPrefixes()) {
                filterRegistration.addMappingForUrlPatterns(EnumSet.of(REQUEST, FORWARD), filterAfterDeclaredFilters, prefix);
            }

            // Additionally map the filter to all paths that were scanned and which are also directly accessible.
            // This is to give the filter an opportunity to block these.
            for (var path : getPublicRootPaths(servletContext)) {
                filterRegistration.addMappingForUrlPatterns(null, false, path + "*");
            }
        }
    }

    /**
     * This will map the {@link FacesServlet} to extensions found during scanning in {@link ApplicationInitializer}. This is invoked by
     * {@link ApplicationListener}, because the {@link FacesServlet} has to be available.
     *
     * @param servletContext The involved servlet context.
     */
    public static void addFacesServletMappings(ServletContext servletContext) {
        if (!isFacesViewsEnabled(servletContext)) {
            return;
        }

        Set<String> encounteredExtensions = getEncounteredExtensions(servletContext);

        if (isEmpty(encounteredExtensions)) {
            return;
        }

        Set<String> mappings = new HashSet<>(encounteredExtensions);
        mappings.addAll(getMappedWelcomeFiles(servletContext));
        mappings.addAll(filterExtension(getMappedResources(servletContext).keySet()));
        mappings.removeIf(DynamicRoutes::isDynamicRoute);

        ServletRegistration facesServletRegistration = getFacesServletRegistration(servletContext);

        if (facesServletRegistration != null) {
            Collection<String> existingMappings = facesServletRegistration.getMappings();

            for (var mapping : mappings) {
                if (!existingMappings.contains(mapping)) {
                    facesServletRegistration.addMapping(mapping);
                }
            }
        }
    }

    /**
     * Register a view handler that transforms a view id with extension back to an extensionless one. This is invoked by {@link ApplicationProcessor}, because
     * the {@link Application} has to be available.
     *
     * @param servletContext The involved servlet context.
     * @param application The involved faces application.
     */
    public static void registerViewHandler(ServletContext servletContext, Application application) {
        if (isFacesViewsEnabled(servletContext) && !isEmpty(getEncounteredExtensions(servletContext))) {
            application.setViewHandler(new FacesViewsViewHandler(application.getViewHandler()));
            registerNavigationHandlerIfNecessary(servletContext, application);
        }
    }

    /**
     * Registers the navigation handler which resolves an outcome spelling out a dynamic route with its segment values already filled in. This is only of use
     * when the application actually declares a dynamic route, so it is skipped otherwise.
     */
    private static void registerNavigationHandlerIfNecessary(ServletContext servletContext, Application application) {
        var dynamicRoutes = DynamicRoutes.get(servletContext);

        if (dynamicRoutes == null || dynamicRoutes.isEmpty()) {
            return;
        }

        var navigationHandler = application.getNavigationHandler();

        // Faces 4.1 declares getNavigationCase on ConfigurableNavigationHandler while Faces 5 merges it into NavigationHandler, so accept either shape.
        if (navigationHandler instanceof ConfigurableNavigationHandler || findMethod(navigationHandler, "getNavigationCase", null, null, null) != null) {
            application.setNavigationHandler(new DynamicRoutesNavigationHandler(navigationHandler));
        }
        else {
            logger.warning(() -> WARNING_UNCONFIGURABLE_NAVIGATION_HANDLER.formatted(navigationHandler.getClass().getName()));
        }
    }

    // Scanning -------------------------------------------------------------------------------------------------------

    /**
     * Scans for faces-views resources recursively.
     *
     * @param servletContext The involved servlet context.
     * @return The views found during scanning, or an empty map if no views encountered.
     */
    static Map<String, String> scanAndStoreViews(ServletContext servletContext, boolean collectExtensions) {
        Map<String, String> collectedViews = new HashMap<>();
        Set<String> collectedExtensions = new HashSet<>();
        Set<String> excludedPaths = new HashSet<>();
        var dynamicRoutes = new DynamicRoutes();

        for (String[] rootPathAndExtension : getRootPathsAndExtensions(servletContext)) {
            String rootPath = rootPathAndExtension[0];

            if (isExcludePath(rootPath)) {
                excludedPaths.add(rootPath.substring(1));
            }
            else {
                String extension = rootPathAndExtension[1];
                scanViews(
                    servletContext, rootPath, servletContext.getResourcePaths(rootPath), collectedViews, extension, collectedExtensions, dynamicRoutes
                );
            }
        }

        collectedViews.keySet().removeIf(collectedView -> excludedPaths.stream().anyMatch(collectedView::startsWith));

        if (!collectedViews.isEmpty()) {
            if (isLowercasedRequestURI(servletContext)) {
                lowercaseCollectedViews(collectedViews);
            }

            servletContext.setAttribute(MAPPED_RESOURCES, unmodifiableMap(collectedViews));
            servletContext.setAttribute(
                REVERSE_MAPPED_RESOURCES, unmodifiableMap(
                    collectedViews.entrySet().stream()
                        .filter(e -> isExtensionless(e.getKey())).collect(toMap(Entry::getValue, Entry::getKey, (l, r) -> l))
                )
            );
            MultiViews.storeResources(servletContext, collectedViews);
            dynamicRoutes.store(servletContext);
            servletContext.setAttribute(EXCLUDED_PATHS, unmodifiableSet(excludedPaths));

            if (collectExtensions) {
                storeExtensions(servletContext, collectedViews, collectedExtensions);
            }
        }

        return collectedViews;
    }

    /**
     * Adds a lowercased mapping for each collected view whose resource name is not already lowercased, so that a lowercased request URI resolves to the same
     * view.
     *
     * @param collectedViews The collected views to be lowercased in place.
     */
    private static void lowercaseCollectedViews(Map<String, String> collectedViews) {
        for (var mapping : new HashSet<>(collectedViews.entrySet())) {
            String resourceName = mapping.getKey();
            String lowercasedResourceName = resourceName.toLowerCase();

            if (!resourceName.equals(lowercasedResourceName)) {
                collectedViews.put(lowercasedResourceName, mapping.getValue());

                if (isExtensionless(resourceName)) {
                    collectedViews.remove(resourceName);
                }
                else {
                    mapping.setValue(null);
                }
            }
        }
    }

    private static void scanAndStoreWelcomeFiles(ServletContext servletContext) {
        URL webXml;

        try {
            webXml = Servlets.getWebXmlURL(servletContext);
        }
        catch (IOException e) {
            throw new IllegalStateException(e);
        }

        Set<String> mappedWelcomeFiles = new LinkedHashSet<>();

        for (var welcomeFile : getNodeTextContents(webXml, "welcome-file-list/welcome-file")) {
            if (isExtensionless(welcomeFile)) {
                mappedWelcomeFiles.add(addLeadingSlashIfNecessary(stripTrailingSlash(welcomeFile)));
            }
        }

        servletContext.setAttribute(MAPPED_WELCOME_FILES, unmodifiableSet(mappedWelcomeFiles));
    }

    @SuppressWarnings("unchecked")
    private static Set<String[]> getRootPathsAndExtensions(ServletContext servletContext) {
        Set<String[]> rootPaths = (Set<String[]>) servletContext.getAttribute(SCAN_PATHS);

        if (rootPaths == null) {
            rootPaths = new HashSet<>();
            rootPaths.add(new String[] { WEB_INF_VIEWS, null });
            Set<String> multiViewsPaths = new HashSet<>();

            for (var rootPath : csvToList(servletContext.getInitParameter(FACES_VIEWS_SCAN_PATHS_PARAM_NAME))) {
                boolean multiViews = MultiViews.isScanPath(rootPath);

                if (multiViews) {
                    rootPath = MultiViews.stripScanPathSuffix(rootPath);
                }

                String[] rootPathAndExtension = rootPath.contains("*") ? rootPath.split(quote("*")) : new String[] { rootPath, null };
                rootPathAndExtension[0] = normalizeRootPath(rootPathAndExtension[0]);
                rootPaths.add(rootPathAndExtension);

                if (multiViews) {
                    multiViewsPaths.add(rootPathAndExtension[0]);
                }
            }

            servletContext.setAttribute(SCAN_PATHS, unmodifiableSet(rootPaths));
            MultiViews.storePaths(servletContext, multiViewsPaths);
        }

        return rootPaths;
    }

    private static void storeExtensions(ServletContext servletContext, Map<String, String> collectedViews, Set<String> collectedExtensions) {
        servletContext.setAttribute(ENCOUNTERED_EXTENSIONS, unmodifiableSet(collectedExtensions));

        if (!collectedExtensions.isEmpty()) {
            MultiViews.storeWelcomeFile(servletContext, collectedViews);
        }
    }

    /**
     * A public path is a path that is also directly accessible, e.g. is world readable. This excludes the special path /, which is by definition world readable
     * but not included in this set.
     */
    @SuppressWarnings("unchecked")
    private static Set<String> getPublicRootPaths(ServletContext servletContext) {
        Set<String> publicRootPaths = (Set<String>) servletContext.getAttribute(PUBLIC_SCAN_PATHS);

        if (publicRootPaths == null) {
            publicRootPaths = new HashSet<>();

            for (String[] rootPathAndExtension : getRootPathsAndExtensions(servletContext)) {
                String rootPath = rootPathAndExtension[0];

                if (!isRoot(rootPath) && !isExcludePath(rootPath) && !startsWithOneOf(rootPath, RESTRICTED_DIRECTORIES)) {
                    publicRootPaths.add(rootPath);
                }
            }

            servletContext.setAttribute(PUBLIC_SCAN_PATHS, unmodifiableSet(publicRootPaths));
        }

        return publicRootPaths;
    }

    /**
     * Scans resources (views) recursively starting with the given resource paths for a specific root path, and collects those and all unique extensions
     * encountered in a flat map respectively set.
     *
     * @param servletContext The involved servlet context.
     * @param rootPath One of the paths from which views are scanned. By default this is typically /WEB-INF/faces-view/
     * @param resourcePaths Collection of paths to be considered for scanning, can be either files or directories.
     * @param collectedViews A mapping of all views encountered during scanning. Mapping will be from the simplified form to the actual location relatively to
     * the web root. E.g key "foo", value "/WEB-INF/faces-view/foo.xhtml"
     * @param extensionToScan A specific extension to scan for. Should start with a ., e.g. ".xhtml". If this is given, only resources with that extension will
     * be scanned. If null, all resources will be scanned.
     * @param collectedExtensions Set in which all unique extensions will be collected. May be null, in which case no extensions will be collected.
     */
    private static void scanViews(
        ServletContext servletContext, String rootPath, Set<String> resourcePaths,
        Map<String, String> collectedViews, String extensionToScan, Set<String> collectedExtensions, DynamicRoutes dynamicRoutes
    )
    {
        if (isEmpty(resourcePaths)) {
            return;
        }

        boolean hasMultiViewsWelcomeFile = MultiViews.hasWelcomeFile(servletContext);

        for (var resourcePath : resourcePaths) {
            var normalizedResourcePath = normalizeResourcePath(servletContext, resourcePath);

            if (isDirectory(normalizedResourcePath)) {
                if (canScanDirectory(rootPath, normalizedResourcePath)) {
                    scanViews(
                        servletContext, rootPath, servletContext.getResourcePaths(normalizedResourcePath), collectedViews, extensionToScan,
                        collectedExtensions, dynamicRoutes
                    );
                }
            }
            else if (canScanResource(normalizedResourcePath, extensionToScan)) {
                scanView(servletContext, rootPath, normalizedResourcePath, collectedViews, collectedExtensions, hasMultiViewsWelcomeFile, dynamicRoutes);
            }
        }
    }

    private static void scanView(
        ServletContext servletContext, String rootPath, String resourcePath,
        Map<String, String> collectedViews, Set<String> collectedExtensions, boolean hasMultiViewsWelcomeFile, DynamicRoutes dynamicRoutes
    )
    {
        // Strip the root path from the current path.
        // E.g. /WEB-INF/faces-views/foo.xhtml will become foo.xhtml if the root path = /WEB-INF/faces-view/
        String resource = stripPrefixPath(rootPath, resourcePath);

        // Store the resource with and without an extension, e.g. store both foo.xhtml and foo
        collectedViews.put(resource, resourcePath);
        String extensionlessResource = stripExtension(resource);
        String extensionlessResourcePath = stripExtension(resourcePath);

        boolean multiViews = MultiViews.isResource(servletContext, extensionlessResourcePath);

        if (DynamicRoutes.isDynamicRoute(extensionlessResource)) {
            dynamicRoutes.add(extensionlessResource, resourcePath, multiViews, isWelcomeFile(servletContext, extensionlessResource));
        }
        else if (multiViews) {
            collectedViews.put(extensionlessResource + MultiViews.SUFFIX, resourcePath);
        }
        else {
            if (hasMultiViewsWelcomeFile) { // This will install forwarding filter on /* and therefore we need to cover / ourselves.
                collectedViews.put(extensionlessResource + "/", resourcePath);
            }

            collectedViews.put(extensionlessResource, resourcePath);

            // If FacesServlet is explicitly mapped on virtual extensions (e.g. when FacesViews is later enabled on a legacy app with *.jsf),
            // then we need to collect them as well so that these can properly be 301-redirected to extensionless one.
            for (var facesServletExtension : getFacesServletExtensions(servletContext)) {
                if (!resourcePath.endsWith(facesServletExtension)) {
                    collectedViews.put(extensionlessResource + facesServletExtension, resourcePath);
                }
            }
        }

        DynamicRoutes.warnIfBracketedFileName(extensionlessResource);

        // Optionally, collect all unique extensions that we have encountered.
        if (collectedExtensions != null) {
            collectedExtensions.add("*" + getExtension(resourcePath));
        }
    }

    private static boolean isWelcomeFile(ServletContext servletContext, String extensionlessResource) {
        return getMappedWelcomeFiles(servletContext).stream().anyMatch(extensionlessResource::endsWith);
    }

    private static String normalizeRootPath(String rootPath) {
        boolean excludePath = isExcludePath(rootPath);
        return addTrailingSlashIfNecessary((excludePath ? "!" : "") + addLeadingSlashIfNecessary(rootPath.substring(excludePath ? 1 : 0)));
    }

    /**
     * ServletContext#getResourcePaths seems broken in quarkus-arquillian. - It contains full path prefix like
     * /tmp/quarkus-arquillian-test123456798/app/META-INF/resources, so it had to be stripped off manually. - Directories does not contain the trailing / in
     * contrary to what {@link ServletContext#getResourcePaths(String)}) javadoc says, so it had to be added manually.
     */
    private static String normalizeResourcePath(ServletContext servletContext, String resourcePath) {
        var webFragmentResource = resourcePath.indexOf(WEB_FRAGMENT_RESOURCE_DIRECTORY);

        if (webFragmentResource > -1) {
            var normalizedResourcePath = resourcePath.substring(webFragmentResource + WEB_FRAGMENT_RESOURCE_DIRECTORY.length() - 1);

            if (!isDirectory(normalizedResourcePath)) {
                try {
                    if (servletContext.getResource(normalizedResourcePath) == null) {
                        normalizedResourcePath += "/";
                    }
                }
                catch (Exception e) {
                    throw new IllegalStateException(e);
                }
            }

            return normalizedResourcePath;
        }

        return resourcePath;
    }

    private static boolean isExcludePath(String rootPath) {
        return rootPath.charAt(0) == '!';
    }

    private static boolean canScanDirectory(String rootPath, String directory) {
        if (!isRoot(rootPath)) {
            // If a user has explicitly asked for scanning anything other than /, every sub directory of it can be scanned.
            return true;
        }

        // For the special root path /, don't scan /WEB-INF, /META-INF and /resources directories.
        return !startsWithOneOf(directory, RESTRICTED_DIRECTORIES);
    }

    private static boolean canScanResource(String resource, String extensionToScan) {

        // If no extension has been explicitly defined, we scan all extensions encountered.
        return (extensionToScan == null) || resource.endsWith(extensionToScan);
    }

    // Helpers for FacesViewsForwardingFilter -------------------------------------------------------------------------

    static ExtensionAction getExtensionAction(ServletContext servletContext) {
        return getEnumInitParameter(servletContext, FACES_VIEWS_EXTENSION_ACTION_PARAM_NAME, ExtensionAction.class, REDIRECT_TO_EXTENSIONLESS);
    }

    static PathAction getPathAction(ServletContext servletContext) {
        return getEnumInitParameter(servletContext, FACES_VIEWS_PATH_ACTION_PARAM_NAME, PathAction.class, SEND_404);
    }

    static boolean isResourceInPublicPath(ServletContext servletContext, String resource) {
        for (var path : getPublicRootPaths(servletContext)) {
            if (resource.startsWith(path)) {
                return true;
            }
        }

        return false;
    }

    /**
     * Obtains the full request URL from the given request and the given resource complete with the query string, but with the extension (if any) cut out. E.g.
     * <code>https://example.com/foo/bar.xhtml?kaz=1</code> becomes <code>https://example.com/foo/bar?kaz=1</code>
     */
    static String getExtensionlessURLWithQuery(HttpServletRequest request, String resource) {
        var queryString = (request.getQueryString() == null) ? "" : ("?" + request.getQueryString());
        String baseURL = getRequestBaseURL(request);
        return baseURL.substring(0, baseURL.length() - 1) + stripExtension(resource) + queryString;
    }

    // Helpers for FacesViewsViewHandler ------------------------------------------------------------------------------

    static boolean isScannedViewsAlwaysExtensionless(ServletContext servletContext) {
        String alwaysExtensionless = servletContext.getInitParameter(FACES_VIEWS_SCANNED_VIEWS_EXTENSIONLESS_PARAM_NAME);
        return isEmpty(alwaysExtensionless) || parseBoolean(alwaysExtensionless);
    }

    static boolean isLowercasedRequestURI(ServletContext servletContext) {
        return parseBoolean(servletContext.getInitParameter(FACES_VIEWS_LOWERCASED_REQUEST_URI_PARAM_NAME));
    }

    @SuppressWarnings("unchecked")
    static Set<String> getFacesServletExtensions(ServletContext servletContext) {
        Set<String> extensions = (Set<String>) servletContext.getAttribute(FACES_SERVLET_EXTENSIONS);

        if (extensions == null) {
            extensions = new HashSet<>();

            for (var mapping : getFacesServletMappings(servletContext)) {
                if (mapping.startsWith("*")) {
                    extensions.add(mapping.substring(1));
                }
            }

            servletContext.setAttribute(FACES_SERVLET_EXTENSIONS, unmodifiableSet(extensions));
        }

        return extensions;
    }

    // Helpers for FacesViewsResourceHandler --------------------------------------------------------------------------

    static String getMappedPath(String path) {
        Map<String, String> mappedResources = getMappedResources(getServletContext());
        return (mappedResources != null && mappedResources.containsKey(path)) ? mappedResources.get(path) : path;
    }

    // Internal helpers -----------------------------------------------------------------------------------------------

    private static <E extends Enum<E>> E getEnumInitParameter(ServletContext servletContext, String name, Class<E> type, E defaultValue) {
        String value = servletContext.getInitParameter(name);

        if (isEmpty(value)) {
            return defaultValue;
        }

        try {
            return Enum.valueOf(type, value.toUpperCase(US));
        }
        catch (Exception e) {
            throw new IllegalArgumentException("Value '%s' is not valid for context parameter '%s'".formatted(value, name), e);
        }
    }

    static Map<String, String> getMappedResources(ServletContext servletContext) {
        return getApplicationAttribute(servletContext, MAPPED_RESOURCES);
    }

    static Map<String, String> getReverseMappedResources(ServletContext servletContext) {
        return getApplicationAttribute(servletContext, REVERSE_MAPPED_RESOURCES);
    }

    static Set<String> getExcludedPaths(ServletContext servletContext) {
        return getApplicationAttribute(servletContext, EXCLUDED_PATHS);
    }

    static Set<String> getEncounteredExtensions(ServletContext servletContext) {
        return getApplicationAttribute(servletContext, ENCOUNTERED_EXTENSIONS);
    }

    static Set<String> getMappedWelcomeFiles(ServletContext servletContext) {
        return getApplicationAttribute(servletContext, MAPPED_WELCOME_FILES);
    }

    static String getFacesServletName(ServletContext servletContext) {
        return getApplicationAttribute(servletContext, FACES_SERVLET_NAME);
    }

    // Utility --------------------------------------------------------------------------------------------------------

    /**
     * Returns whether FacesViews feature is enabled. That is, when the <code>org.omnifaces.FACES_VIEWS_ENABLED</code> context parameter value does not equal
     * <code>false</code>.
     *
     * @param servletContext The involved servlet context.
     * @return Whether FacesViews feature is enabled.
     * @since 2.5
     */
    public static boolean isFacesViewsEnabled(ServletContext servletContext) {
        Boolean enabled = getApplicationAttribute(servletContext, ENABLED);

        if (enabled == null) {
            enabled = !"false".equals(servletContext.getInitParameter(FACES_VIEWS_ENABLED_PARAM_NAME));
            servletContext.setAttribute(ENABLED, enabled);
        }

        return enabled;
    }

    /**
     * Returns whether MultiViews feature is enabled. This is implicitly enabled when <code>org.omnifaces.FACES_VIEWS_SCAN_PATHS</code> context parameter value
     * is suffixed with <code>/*</code>.
     *
     * @param servletContext The involved servlet context.
     * @return Whether MultiViews feature is enabled.
     * @since 2.5
     */
    public static boolean isMultiViewsEnabled(ServletContext servletContext) {
        return MultiViews.isEnabled(servletContext);
    }

    /**
     * Returns whether MultiViews feature is enabled on given request.
     *
     * @param request The involved HTTP servlet request.
     * @return Whether MultiViews feature is enabled on given request.
     * @since 2.6
     */
    public static boolean isMultiViewsEnabled(HttpServletRequest request) {
        return MultiViews.isEnabled(request);
    }

    /**
     * Returns whether MultiViews feature is enabled on the given resource.
     *
     * @param servletContext The involved servlet context.
     * @param resource The resource.
     * @return Whether MultiViews feature is enabled on the given resource.
     * @since 3.6
     */
    public static boolean isMultiViewsEnabled(ServletContext servletContext, String resource) {
        return MultiViews.isEnabled(servletContext, resource);
    }

    /**
     * Strips any mapped welcome file prefix path from the given resource.
     *
     * @param servletContext The involved servlet context.
     * @param resource The resource.
     * @return The resource without the welcome file prefix path, or as-is if it didn't start with this prefix.
     * @since 2.5
     */
    public static String stripWelcomeFilePrefix(ServletContext servletContext, String resource) {
        for (var mappedWelcomeFile : getMappedWelcomeFiles(servletContext)) {
            if (resource.endsWith(mappedWelcomeFile)) {
                return addTrailingSlashIfNecessary(resource.substring(0, resource.length() - mappedWelcomeFile.length()));
            }
        }

        return resource;
    }

    /**
     * Strips any special '/WEB-INF/faces-views' prefix path from the given resource.
     *
     * @param resource The resource.
     * @return The resource without the special prefix path, or as-is if it didn't start with this prefix.
     */
    public static String stripFacesViewsPrefix(String resource) {
        return stripPrefixPath(WEB_INF_VIEWS, resource);
    }

}
