/*
 * Copyright OmniFaces
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 */
package org.omnifaces.taghandler;

import static org.omnifaces.util.ComponentsLocal.createValueExpression;

import java.io.IOException;

import jakarta.faces.component.UIComponent;
import jakarta.faces.view.facelets.FaceletContext;
import jakarta.faces.view.facelets.TagConfig;
import jakarta.faces.view.facelets.TagHandler;

import org.omnifaces.config.OmniFaces;
import org.omnifaces.el.DelegatingVariableMapper;
import org.omnifaces.vdl.FacesAttribute;
import org.omnifaces.vdl.FacesTagHandler;

/**
 * <p>
 * The <code>&lt;o:tagAttribute&gt;</code> is a tag handler that can be used to explicitly declare a tag attribute on a Facelets tag file. This makes sure that
 * any tag attribute with the same name on a parent tag file is cleared out, which does not properly happen in Mojarra.
 * <p>
 * Consider the following custom tag structure:
 *
 * <pre>
 * &lt;my:tag id="foo"&gt;
 *     &lt;my:tag id="bar" /&gt;
 * &lt;/my:tag&gt;
 * </pre>
 * <p>
 * Inside the nested tag, the <code>#{id}</code> will just evaluate to <code>"bar"</code>. However, if this isn't declared on the nested tag like so,
 *
 * <pre>
 * &lt;my:tag id="foo"&gt;
 *     &lt;my:tag /&gt;
 * &lt;/my:tag&gt;
 * </pre>
 * <p>
 * then <code>#{id}</code> of the nested tag would evaluate to <code>"foo"</code> instead of <code>null</code>, even when you explicitly specify the attribute
 * in the <code>*.taglib.xml</code> file.
 * <p>
 * This tag handler is designed to overcome this peculiar problem and unintuitive behavior of nested tagfiles in Mojarra.
 *
 * <h2>Usage</h2>
 * <p>
 * Just declare the attribute name in top of the tagfile as below.
 *
 * <pre>
 * &lt;o:tagAttribute name="id" /&gt;
 * </pre>
 * <p>
 * You can optionally provide a default value.
 *
 * <pre>
 * &lt;o:tagAttribute name="type" default="text" /&gt;
 * </pre>
 *
 * Since OmniFaces 2.7/3.2 there is a special case for a <code>&lt;o:tagAttribute name="id"&gt;</code> without a default value: it will override any
 * autogenerated ID into the form of <code>j_ido[tagId]</code> where <code>[tagId]</code> is the <code>&lt;o:tagAttribute&gt;</code> tag's own unique ID. This
 * is autogenerated per tag file invocation, so nested invocations of the same tag file each get their own ID.
 *
 * <h2>Scope</h2>
 * <p>
 * The declaration only shields against enclosing tag files which declare their attributes as well, so every tag file in a nesting chain must declare its
 * attributes. A tag file which does not declare them is not a scope boundary, and whether its attributes are then visible to a nested tag file is up to the
 * Faces implementation.
 * <p>
 * Only a tag attribute of an enclosing tag file is shielded. A variable of the same name which an enclosing tag file did not declare as a tag attribute, such
 * as one set by <code>&lt;ui:param&gt;</code> or <code>&lt;c:set&gt;</code>, is left alone, and whether it is visible inside a nested tag file at all is up to
 * the Faces implementation. Setting a name which the same tag file already declared keeps that name shielded for the remainder of that tag file. Declaring the
 * attribute also does not affect the enclosing tag file: it keeps its own value in the markup which follows the nested tag file.
 *
 * @author Arjan Tijms.
 * @since 2.1
 */
@FacesTagHandler(namespace = OmniFaces.OMNIFACES_NAMESPACE)
public class TagAttribute extends TagHandler {

    private static final String ID_ATTRIBUTE = "id";
    private static final String ID_PREFIX = "j_ido";

    @FacesAttribute(required = true, description = "The declared attribute name.")
    private final String name;

    @FacesAttribute(name = "default", description = "The default value to be used when actual value is null.")
    private final jakarta.faces.view.facelets.TagAttribute defaultValue;

    /**
     * The tag constructor.
     *
     * @param config The tag config.
     */
    public TagAttribute(TagConfig config) {
        super(config);
        name = getRequiredAttribute("name").getValue();
        defaultValue = getAttribute("default");
    }

    @Override
    public void apply(FaceletContext context, UIComponent parent) throws IOException {
        var variableMapper = new DelegatingVariableMapper(context.getVariableMapper());
        context.setVariableMapper(variableMapper);
        var valueExpression = variableMapper.resolveWrappedVariable(name);

        if (valueExpression == null) {
            if (defaultValue != null) {
                valueExpression = defaultValue.getValueExpression(context, Object.class);
            }
            else if (ID_ATTRIBUTE.equals(name)) {
                valueExpression = createValueExpression(
                    context.getFacesContext(), "#{'" + ID_PREFIX + context.generateUniqueId(this.tagId) + "'}",
                    String.class
                );
            }
        }

        variableMapper.declareVariable(name, valueExpression);
    }

}
